version: "3.7"

services:
  mongodb:
    image: mongo:7
    networks:
      - minha_rede
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: GERAR-SENHA-ACESSO-AO-MONGO # GERAR EM https://www.avast.com/random-password-generator#pc    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

networks:
  minha_rede:
    external: true
    name: minha_rede


volumes:
  mongodb_data:
    external: true
    name: mongodb_data

  mongodb_config:
    external: true
    name: mongodb_config
