version: "3.7"

services:
  postgres:
    image: postgres:latest
    networks:
      - minha_rede
    entrypoint: docker-entrypoint.sh
    command: [postgres, --max_connections=200]
    # ports:
    #  - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=GERAR-NOVA-SENHA # GERAR EM https://www.avast.com/random-password-generator#pc    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks:
  minha_rede:
    external: true
    name: minha_rede
