version: "3.7"
services:
  qdrant:
    image: qdrant/qdrant:latest
    networks:
      - minha_rede #NOME DA REDE UTILIZADA NAS STACKS ANTERIORES
    volumes:
      - qdrant_storage:/qdrant/storage
      - qdrant_snapshots:/qdrant/snapshots
      - qdrant_tls:/qdrant/tls
    environment:
      QDRANT__TELEMETRY_DISABLED: 'true'
      QDRANT__SERVICE__ENABLE_CORS: 'true'
      QDRANT__SERVICE__ENABLE_TLS: 'false'
      QDRANT__SERVICE__VERIFY_HTTPS_CLIENT_CERTIFICATE: 'false'
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__API_KEY: 'GERAR-NOVA-SENHA' # GERAR EM https://www.avast.com/random-password-generator#pc    
      QDRANT__SERVICE__READ_ONLY_API_KEY: 'GERAR-NOVA-SENHA' # GERAR EM https://www.avast.com/random-password-generator#pc    
    # uncomment to expose qdrant port to host
    ports:
     - "6333:6333"     
     - "6334:6334"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        # Define os limites de recursos do serviço
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.qdrant.rule=Host(`qdrant.SEUDOMINIO.com`) # DOMINIO PARA ACESSAR O DASHBOARD
        - traefik.http.routers.qdrant.entrypoints=websecure
        - traefik.http.routers.qdrant.tls.certresolver=letsencryptresolver
        - traefik.http.services.qdrant.loadBalancer.server.port=6333
        - traefik.http.routers.qdrant.service=qdrant

networks:
  minha_rede:  # NOME DA REDE UTILIZADA NAS STACKS ANTERIORES
    name: minha_rede # NOME DA REDE UTILIZADA NAS STACKS ANTERIORES
    external: true 

volumes:
  qdrant_storage:
    external: true
    name: qdrant_storage
  qdrant_snapshots:
    external: true
    name: qdrant_snapshots
  qdrant_tls:
    external: true
    name: qdrant_tls
